### ISSUE TITLE
hodoku.hcfg corrupted Config Bug, @PseudoFish fix

### ISSUE THREAD

**Issue by 1to9only** [1to9only/HoDoKu#15]
To import [PseudoFish](https://github.com/PseudoFish/Hodoku/commit/ef6ce74f38b64f80ccecd709563b9d73abdce547) Config Fix where if the config [file hodoku.hcfg] was corrupt, Hodoku would fail to re-generate the config file. I _[PseudoFish]_ verify if the file loaded is empty, if it is, I _[PseudoFish]_ delete it which forces Hodoku to re-generate a default config file.

To recreate the problem, I _[1to9only]_ made the hodoku.hcfg files in the Hoduku and TEMP folders 0 bytes.
- Start Hodoku
```
java.exe -jar Hodoku.jar /gui hodoku.hcfg
```
- Log outout (edited):
```
INFO: Reading options from C:\Temp\hodoku.hcfg
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
Continuing ...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
        at sudoku.Options.readOptions(Options.java:869)
        at sudoku.Options.readOptions(Options.java:862)
        at sudoku.Options.getInstance(Options.java:643)
        at sudoku.Main.main(Main.java:350)
```

**Comment by 1to9only** [comment]
Log output (edited):
```
INFO: Reading options from C:\Temp\hodoku.hcfg
C:\Temp\hodoku.hcfg is corrupted, deleting...
Nov 01, 2021 8:50:14 AM sudoku.Options readOptions
INFO: No config file found
Nov 01, 2021 8:50:14 AM sudoku.Options writeOptions
INFO: Writing options to C:\Temp\hodoku.hcfg
...
CONFIG: Reading options from D:\Hodoku-2.2.4\hodoku.hcfg
Nov 01, 2021 8:50:14 AM sudoku.Options readOptions
INFO: Reading options from D:\Hodoku-2.2.4\hodoku.hcfg
D:\Hodoku-2.2.4\hodoku.hcfg is corrupted, deleting...
Nov 01, 2021 8:50:14 AM sudoku.Options readOptions
INFO: No config file found
```
