### ISSUE TITLE
XY-Chain comparator Bug, @PseudoFish fix

### ISSUE THREAD

**Issue by 1to9only** [1to9only/HoDoKu#16]
To import [PseudoFish](https://github.com/PseudoFish/Hodoku/commit/523fdc9d0d31be2a3f7ceab3fa34542475cf628e) XY-Chain Bug Fix where a comparator bug leading to a crash while attempting to solve certain puzzles using XY-Chains.

XY-Chain Bug, to recreate:
- Paste this grid:
```
5.2.8..4.93..64.........93.....7.6.9..6....58.....62...7..9....4....38....3.5...7
```
- IllegalArgumentException:
```
Exception in thread "Thread-9" java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
        at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1506)
        at java.util.ArrayList.sort(ArrayList.java:1464)
        at java.util.Collections.sort(Collections.java:143)
        at solver.ChainSolver.getXYChains(ChainSolver.java:251)
        at solver.ChainSolver.getStep(ChainSolver.java:176)
        at solver.SudokuStepFinder.getStep(SudokuStepFinder.java:265)
        at solver.SudokuSolver.getHint(SudokuSolver.java:465)
        at solver.SudokuSolver.solve(SudokuSolver.java:238)
        at solver.SudokuSolver.solve(SudokuSolver.java:175)
        at solver.SudokuSolver.solve(SudokuSolver.java:161)
        at sudoku.SolverProgressDialog.run(SolverProgressDialog.java:120)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by 1to9only** [comment]
The fix is to uncomment these lines in SolutionStep.java:
```
2010,2014c2010,2014
< //            // change 20110512: short chains first!
< //            int chainDiff = compareChainLengths(o);
< //            if (chainDiff != 0) {
< //                return chainDiff;
< //            }
---
>             // change 20110512: short chains first!
>             int chainDiff = compareChainLengths(o);
>             if (chainDiff != 0) {
>                 return chainDiff;
>             }
```
However, those lines were commented out by hobiwan a long time ago to fix an ALS-Chains sorting problem, see [here](https://github.com/1to9only/HoDoKu/commit/7b85f5c34774dcd6939ec2b65877469711f8ea09#diff-49f13718b5ccbcb88cecca1387290c553e733d7276248ca193946930c0b2a3f8).
```
Commits on Mar 31, 2012
Fixed: #3513603: Search for all steps ignores ALS types
fixed a problem with sorting: ALS-Chains were sometimes sorted incorrectly
```
So fixing this issue will likely bring back the old ALS-Chains sorting problem!!
